exec-once = awww-daemon
exec-once = sleep 2 && awww img /home/kurasako/Загрузки/waguri-kaoruko.3840x2160.mp4
exec-once = qs -c caelestia
exec-once = nwg-dock-hyprland -i 56 -mb 12 -nolauncher -d -hd 0

# Блокировка экрана
bind = SUPER, L, exec, loginctl lock-session

# Caelestia shortcuts
bind = SUPER, A,      exec, qs msg -c caelestia callmethod shortcuts.launcher
bind = SUPER, D,      exec, qs msg -c caelestia callmethod shortcuts.dashboard
bind = SUPER, S,      exec, qs msg -c caelestia callmethod shortcuts.sidebar
bind = SUPER, Escape, exec, qs msg -c caelestia callmethod shortcuts.session
