exec-once = awww-daemon
exec-once = sleep 1 && awww img /home/kurasako/devushka_gejmpad_gejmer_1313139_3840x2160.jpg
exec-once = qs -c caelestia
exec-once = nwg-dock-hyprland -i 40 -mb 10 -nolauncher -d -hd 0
